FROM tomcat:9.0-jdk11
COPY /var/lib/jenkins/workspace/Project/Industry Grade Project I - Java Project/ABC Technologies/target/ABCtechnologies-1.0.war  /opt/tomcat/webapps/
CMD ["catalina.sh", "run"]


