FROM iamdevopstrainer/tomcat:base
COPY /var/lib/jenkins/workspace/Project/Industry\ Grade\ Project\ I\ -\ Java\ Project/ABC\ Technologies/target/ABCtechnologies-1.0.war /usr/local/tomcat/webapps/
CMD ["catalina.sh", "run"]


