# Use the official Tomcat base image
FROM tomcat:9.0

# Remove the default webapps to ensure a clean slate
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy the WAR file from your Jenkins workspace to the Docker image
# Adjust the path to where Jenkins outputs the WAR file
COPY target/ABCtechnologies-1.0.war /usr/local/tomcat/webapps/ROOT.war

# Expose the port Tomcat is running on
EXPOSE 8080

# Start Tomcat
CMD ["catalina.sh", "run"]



